# templates/service.yaml
{{- range $i := until (int .Values.agents.count) }}
---
apiVersion: v1
kind: Service
metadata:
  name: agent-node{{ add $i 1 }}
spec:
  type: NodePort
  selector:
    app: agent-node{{ add $i 1 }}
  ports:
    - name: http
      port: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: agent-node{{ add $i 1 }}-ipfs
spec:
  type: NodePort
  selector:
    app: agent-node{{ add $i 1 }}
  ports:
    - name: ipfs
      port: 4002
      targetPort: 4002
{{- end }} 
