apiVersion: v1
kind: Pod
metadata:
  name: agent-node2
  labels:
    app: agent-node2
spec:
  volumes:
  - name: node2
    hostPath:
      path: /mnt/deploy/node2
      type: Directory
  containers:
  - name: agent-container2
    image: lightstreams/leth-0.33.0-alpha-demo:latest
    imagePullPolicy: Never 
    volumeMounts:
      - name: node2
        mountPath: /srv/lightchain
    env:
      - name: AGENT_HOME
        value: "/root/.lightstreams_1"
    ports:
      - containerPort: 4002
      - containerPort: 9091
    command:
      - bash
      - "-c"
      - |

        if [ ! -f $AGENT_HOME/config.json ]; then
          leth init --nodeid=1 --network=sirius --lightclient=true --federation=false --demo=true --blockchain_url=http://$VALIDATOR_ETH2_PORT_8545_TCP_ADDR:8545 || exit 1
          mkdir -p $AGENT_HOME/sirius/database/keystore
          
          cp -r /srv/lightchain/config/UTC--2024-03-31T17-53-19.797023000Z--80b31f1d87aa472c9ea8e88c58ffd6ad231234f2 $AGENT_HOME/sirius/database/keystore
          cp -r /srv/lightchain/config/UTC--2019-01-16T08-35-20.225Z--61f3b85929c20980176d4a09771284625685c40e $AGENT_HOME/sirius/database/keystore

          cp -r /srv/lightchain/ipfs.config $AGENT_HOME/ipfs/config
          
        fi

        LETH_LOG_LEVEL=debug leth run --nodeid=1 --network=sirius --https
